// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtvyqspntviaglbnmzpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10dnlxc3BudHZpYWdsYm5tenBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTE3MDUsImV4cCI6MjA2NzcyNzcwNX0.D2Evy7jA_PCJHxT3KZhRP2rj_ERAloiPOw2kf30ucRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});